import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  <>
    <html lang="en" data-theme="black">
      <head>
        <meta name="title" content="Kevin Lee CV"/>
        <meta name="description" content="Cloud Porfolio"/>
        <meta name="author" content="Kevin Lee"/>
        <meta name="keywords" content="AWS, Cloud, CI/CD, S3, Cloudfront, React, Python, Bash, Porfolio, SIEM, Lambda, Splunk"/>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  </>
  )
}
